# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '\u7537'), ('famale', '\u5973')], default='\u7537', max_length=8),
        ),
    ]
