# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='openid')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u6635\u79f0')),
                ('sex', models.CharField(blank=True, choices=[('1', '\u7537'), ('2', '\u5973'), ('0', '\u672a\u77e5')], default='0', max_length=8, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('headimgurl', models.CharField(blank=True, max_length=500, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
