# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_login', '0003_declareprofile_imgkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declareprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='declareprofile',
            name='imgkey',
        ),
    ]
