# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_login', '0004_auto_20181121_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declareprofile',
            options={'verbose_name': '\u8868\u767d\u4fe1\u606f', 'verbose_name_plural': '\u8868\u767d\u4fe1\u606f'},
        ),
    ]
